<?php
$productId =  $block->getCurrentProduct()->getId();
$product = $block->getProductCollection($productId);
$currency_symbol = $block->getCurrencySymbol();

if ($product->getCustomAttribute('packing_charge') !== null) { ?>
<div class = "chagre">
   <h3 class="text-msg"><?= $escaper->escapeHtml(__('Product have the extra packing charge')) ?></h3>
   <?php echo "Packing Charge  ".$currency_symbol.$product->getCustomAttribute('packing_charge')->getValue(); ?>
</div>
<?php } ?>